name: cuda
services:
  devel:
    build:
      context: ../
      dockerfile: docker/Dockerfile
      target: builder
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    network_mode: host
    stdin_open: true
    tty: true
    volumes:
      - ../:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:1
    working_dir: /app
    devices:
      - /dev/video0:/dev/video0
